### ISSUE TITLE
Switching between tabs makes Strudel unresponsive

### ISSUE THREAD

**Issue by Bubobubobubobubo** [tidalcycles/strudel#108]
The bug was found using Google Chrome (latest version) on a MacBook Pro 13" (latest OS). In order to reproduce it, open Strudel in one tab and two or three other random tabs (like the ToneJS API doc and a few google queries). Switch from Strudel to documentation while running a moderately complex / dense pattern. After switching back by alt-tabbing, Strudel REPL stops rendering sound and appears to be loading for an undefinite time. It can sometimes resume its course or, in other cases, crash.

**Browser plugins**: Vimium, Dark Reader, uBlock Origin. 
**Chrome version**: 101.0.4951.54
**MacOS version**: 12.2.1 (21D62)

I don't know a lot about web browsers but I wonder if this could be linked to a browser extension altering Strudel behavior somehow. It could also be because my patterns were making extensive use of ToneJS, but nothing fancy really (monosynth with custom parameters).

Happy to help to investigate this issue by running tests or by looking at page performance :).

**Comment by felixroos** [comment]
This could happen due to requestAnimationFrame being halted when the tab is in the background, causing the lastFrame time to stick at that moment in time. When the Strudel tab is refocused, the animation loop will continue, causing the next frame to query from the sticky lastFrame time to the (much later) current time, resulting in a expensive query + an expensive paint for larger spans. So at some time of inactivity, it will freeze the page. I will try to confirm this hypothesis later
