### ISSUE TITLE
Perf on repl

### ISSUE THREAD

**Issue by puria** [tidalcycles/strudel#20]
Ciao ;)
<3 you are doing a super great job!

I was looking at the perf, a little bit, and before there were a lot of repaintings while the notes where highlighted (maybe some useMemo, may help) and also find out:

![Screenshot 2022-02-27 at 16 39 50](https://user-images.githubusercontent.com/10379/155889287-247af713-a957-4690-9dff-720cf0f1c3bd.png)

That make a slow function call (each cycle?), maybe now that the codebase is small, could be narrowed down easier...

I wish I had some time, just those extra two hours during the day, ahahah if you think can help, I can investigate more

**Comment by puria** [comment]
Seems that the bottleneck comes from tonejs as a first impression...

**Comment by felixroos** [comment]
Thanks for looking into this. Since 1375932c05cea422500a9328fec3207ac4e1a64c , highlighting perf should be improved, as painting is not triggered directly in schedule callback anymore, as recommended [here](https://github.com/Tonejs/Tone.js/wiki/Performance). Another thing that requires a solution is that each reevaluation will reinstantiate Tone.js instances without disposing the old ones. @charlieroberts started looking into this. If the issues with Tone.js cannot be fixed, we might switch to another audio backend. But still, there could be opportunities for improvement in other areas.

**Comment by yaxu** [comment]
Shall we close this for now?

**Comment by puria** [comment]
Please!
