### ISSUE TITLE
Add Search

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#468]
![image](https://user-images.githubusercontent.com/12023032/220421029-19e7799d-207c-4ffc-a91b-8f4f7e43d019.jpeg)

**Comment by jarmitage** [comment]
Docs are starting to get quite large now, would be great to add this

**Comment by ilesinge** [comment]
I'm currently working on integrating search to the website (the components were all in the code, it just needs a bit of styling).

**Comment by felixroos** [comment]
> I'm currently working on integrating search to the website (the components were all in the code, it just needs a bit of styling).

great! yeah it's half finished, tho the algolia crawler also needs a bit of fine tuning, iirc not all pages are crawled yet. But it would be a good start if the search would at least be there :) thanks for looking into it

**Comment by ilesinge** [comment]
If you could give me a hint of how the Algolia crawler works I can look into it also?

**Comment by felixroos** [comment]
> If you could give me a hint of how the Algolia crawler works I can look into it also?

just send me your mail on discord and I'll give you an invite

**Comment by ilesinge** [comment]
Search can be added with the PR #827 
As discussed though, the Algolia index is not up to date since the migration to strudel.cc
And updating the crawler means having a new domain validated on Algolia, but it seems Strudel account is limited on the old domain name.

@felixroos We can contact Algolia support (by email) to have a new domain validated for Strudel on this page: https://crawler.algolia.com/admin/domains
Should I ask them or do you prefer to do it ?

I imagine that the best next step would be to set up a separate strudel.cc index and to have the crawler fill it (rather than update the current strudel.tidalcycles.org index, which would risk creating double documents), then move the search client to the new index.

**Comment by felixroos** [comment]
> Search can be added with the PR #827 As discussed though, the Algolia index is not up to date since the migration to strudel.cc And updating the crawler means having a new domain validated on Algolia, but it seems Strudel account is limited on the old domain name.
> 
> @felixroos We can contact Algolia support (by email) to have a new domain validated for Strudel on this page: https://crawler.algolia.com/admin/domains Should I ask them or do you prefer to do it ?
> 
> I imagine that the best next step would be to set up a separate strudel.cc index and to have the crawler fill it (rather than update the current strudel.tidalcycles.org index, which would risk creating double documents), then move the search client to the new index.

i wonder why the old domain doesn't show the new site. It should be set up as a redirect, but it seems some people still see the old site without getting a redirect. This could also be confusing the crawler. Maybe there is a way to just keep the algolia setup but make sure the old urls just point to the new site? Although that already works for me, if I go to https://strudel.tidalcycles.org/workshop/pattern-effects it automatically redirects to https://strudel.cc/workshop/pattern-effects. not sure why this is not working for the algolia crawler. @yaxu an idea?

**Comment by ilesinge** [comment]
If fact the Algolia crawler only goes to domains that have been whitelisted, and strudel.cc is not in the list of whitelisted domains for the Strudel application.
I just sent Algolia support a request to whitelist the new domain.

**Comment by ilesinge** [comment]
The strudel.cc domain was added, and I updated the crawler. **Now all pages are indexed.** We could still finetune the data extraction to have the right level of informations in the search snippets, but it seems to be globally good enough.

There are a few non-blocking crawler errors though:
- Some 404, fixed in this PR: https://github.com/tidalcycles/strudel/pull/838
- Some 301,302: For some reason, the non-slash-ending URLs are redirected to their slash-ending counterparts: https://strudel.cc/learn/effects to https://strudel.cc/learn/effects/
=> The result is that all results use the slash-ending version while the navigation in the documentation uses the non-slash-ending URLs

In order to remove the duplicate URLs:
- Is there a way to disable the non-slash-to-slash redirection (on github or whatever the server or proxy) ?
- Otherwise would that be OK to use the slash-ending version on all documents ?

**Comment by felixroos** [comment]
> In order to remove the duplicate URLs:
> 
>     * Is there a way to disable the non-slash-to-slash redirection (on github or whatever the server or proxy) ?
> 
>     * Otherwise would that be OK to use the slash-ending version on all documents ?

the redirection is default in gh pages and cannot be changed, but the slashless links could be refactored.
see https://github.com/tidalcycles/strudel/issues/841 for more info (trailing slashes are a deeper rabbit hole than one might think :P)

**Comment by felixroos** [comment]
@ilesinge i guess we can close this now, or are there any more loose ends regarding search?

**Comment by ilesinge** [comment]
It seems all good 👍
