### ISSUE TITLE
Control name aliases

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#496]
We're missing some aliases from tidal like `sound` for sound, `sz` for size, etc.

We do have `bpf`, `lpf`, `hpq` etc but as separate controls from the superdirt 'standard' `bandf` ,`cutoff`, `hresonance` etc. The synths honour both rather.

Really SuperDirt should support these nicer / more consistent shorthands but it doesn't yet. So I think I'll mirror the aliases from tidal in strudel for now.

**Comment by felixroos** [comment]
ok.. so the idea is that the same name is used internally for every alias of the same group?

e.g. `bpf(1000)` and `bandf(1000)` both create `{ bandf: 1000 }` ?

I think it's a good idea, as it simplifies a few things:

- the outputs only need to handle the internal name instead of destructuring all aliases. e.g. [this line](https://github.com/tidalcycles/strudel/blob/main/packages/webaudio/webaudio.mjs#L222) and similar ones are not needed anymore
- mixing aliases is not a problem, currently `bandf(1000).mul(bpf(2))` won't work

maybe we don't even need 2 separate lists? the current format for each item in `generic_params` is:

```js
['f', 'bandf', 'A pattern of numbers from 0 to 1. Sets the center frequency of the band-pass filter.']
```

this format never changed since it was ported from python. we're actually only using the `bandf`, discarding the first and third element. we could simplify things by just using a list like this one:

```js
const generic_params = [
  ['bandf', 'bpf'],
  ['delayfeedback', 'delayfb', 'dfb']
  /* ... */
]
```

here, each group of aliases is one array, where the first element is the internal name, and the rest are aliases

the jsdoc can also be placed above each group like:

```js
const generic_params = [
  /**
   * Sets the center frequency of the **b**and-**p**ass **f**ilter.
   *
   * @name bpf
   * @param {number | Pattern} frequency center frequency
   * @synonyms bandf
   * @example
   * s("bd sd,hh*3").bpf("<1000 2000 4000 8000>")
   *
   */
  ['bandf', 'bpf'],
/* ... */
]
``` 

having defined the group of aliases in source, we can also scrap the `@synonyms` tag, as it is now redundant.
The tag is currently used to render ["Synonyms: ..."](https://strudel.tidalcycles.org/learn/effects#bpf) in the [JsDoc component](https://github.com/tidalcycles/strudel/blob/88e8368022c0f34e7db3b5595cd3f92766599d5b/website/src/docs/JsDoc.jsx#L13), which can be refactored to use the list.

While using the supercollider compatible names internally is fine, I'd still find it more accessible to keep the more logical names as documentation headlines. This is just much more easy to read and understand

![image](https://user-images.githubusercontent.com/12023032/222240499-34964e26-05fd-4ac5-afd8-c337c79cc731.png)

**Comment by yaxu** [comment]
Yep that all makes sense, I'll have another look..

**Comment by yaxu** [comment]
Ok I tidied the controls into a single list of lists. Not sure what to do with refactoring the jsdoc component, so will leave that to you if it's ok?

https://github.com/tidalcycles/strudel/pull/497/commits/75e7d454a5fa7791b017344eb91ccafe7c573a82

**Comment by felixroos** [comment]
ok the synonyms can't actually be removed because they are also used for other aliases like cat / slowcat etc.. so there is a little bit of redundancy in the controls, but at least they are side by side. I've now added the missing ones and simplified the handling of the controls in the webaudio output

**Comment by yaxu** [comment]
Ok super.. Ready for merge?

**Comment by felixroos** [comment]
> Ok super.. Ready for merge?

yep
