### ISSUE TITLE
binary pattern reset function

### ISSUE THREAD

**Issue by felixroos** [tidalcycles/strudel#53]
I don't know if this exists in tidal, but it would be fabulous if there was something like that:

```js
"c3 e3".reset("<x [x x]>")
```

being equivalent to `"<[c3 e3] [c3 c3]>"`. So the binary pattern will reset the input pattern each time there is a true event. 

In the example, this is looks pretty boring, but for composing, this opens many doors, for example making sure the bass lines always lands on the root when the chord / scale changes. 

Here is an [example](https://tinyurl.id/lzhOu) of a bass line that doesn't land on the 1 for the last note:

```js
"0 4".scale(
  sequence('C major', ['D dorian', 'G mixolydian']).slow(2)
)
```

The output is equivalent to `"<[c3 g3] [d3 d4]>"` with the indices `"<[0 4] [0 4]>"`.

Ideally, the last note should be a g3, index 0 in 'G mixolydian' which starts there.
A human bass player would almost always play the root note on the first beat of a new scale / chord.

To mimic that behavior, we could use the not yet existing reset function:

```js
const scales = sequence('C major', ['D dorian', 'G mixolydian']).slow(2)
"0 4".reset(scales).scale(scales)
```

This will reset the "0 4" each time the scale changes (any scale is true), creating this index pattern

```js
"<[c3 g3] [d3 g3]>"
// "<[0 4] [0 0]>"
```

... which is what we want in that case. This is not only useful for basslines, but also arpeggios or glitchy retriggering patterns.
This will be fantastic for any type of dynamic groove!

**Comment by yaxu** [comment]
No this isn't in tidal but has been requested before.

Instead of resetting the clock to `0`, you might want to reset it to the next bar/quantum/modulo of the cycle count.

I think this is related to patterning the `cps`, as this resetting is a kind of clock operation. Often you'd want to do this to only part of a pattern. But that might be true of `cps`as well, i.e. you might want to change the `slowing` of a part of pattern without skipping events.

**Comment by yaxu** [comment]
Solved in https://github.com/tidalcycles/strudel/pull/88/
