### ISSUE TITLE
distribute desktop app

### ISSUE THREAD

**Issue by roipoussiere** [tidalcycles/strudel#573]
It could be practical to allow users to use Strudel as a desktop app, without using the browser.

I noticed in the [offline section](https://strudel.tidalcycles.org/learn/pwa) in the docs that it can be done with `npx nativefier strudel.tidalcycles.org`, but it's still an extra step for end users.

My suggestion is to package Strudel for main platforms (Linux/Mac/Windows) in each major release using GitHub actions, so binaries will be available in the release section.

It can be done with [electron-build](https://www.electron.build/) or [tauri](https://tauri.app/v1/guides/building/linux).

I can eventually work on it if you like the idea.

**Comment by felixroos** [comment]
Hey! Thank you for all the ideas you've added :) 

About the desktop app: having the option to install a desktop app from a chromium based browser (PWA) is already a good start, but of course, you can do much more with a full desktop app + non chromium users can use it too.
The downside is that you have to distribute binaries with every release.

I would advise against electron, because the binaries are really large and running them takes a lot of memory. 
Tauri looks great, it also [seems to integrate well with vite](https://tauri.app/v1/guides/getting-started/setup/vite/).
So probably the existing project structure could stay as is, just some additional tauri related files + desktop build task(s).
You can also use [node with tauri](https://marcin.page/posts/tauri-+-nodejs:-alternative-to-electron/), which would probably make sense.

The desktop app could add additional features like a file system integration to load samples, osc / midi / ableton link etc..

If you want to work on it, feel free to go ahead. I am also open to talk more about how it should integrate / features / distribution etc..

**Comment by roipoussiere** [comment]
Thank you for your response!
I will try to do something with Tauri. :)

Some interesting features I think about:
- some cli options to define UI preferences (default theme, disable the welcome message, etc);
- convert code into music file via cli;
- integration with an external IDE;
- start a web server to allow multi-user sessions.

**Comment by felixroos** [comment]
> I will try to do something with Tauri. :) 

great!

> some cli options to define UI preferences (default theme, disable the welcome message, etc);

As of now, the welcome message will only appear once. As soon as you select another tab or close the bottom bar, it will stay that way. the same goes for the settings (including theme) and code in the editor. Not sure if that's really needed then.

> convert code into music file via cli;

that would be amazing. 

> integration with an external IDE

there is a prototype for vs code somewhere. but in many cases, it can be tricky to get the highlighting right.

> start a web server to allow multi-user sessions.

see https://github.com/tidalcycles/strudel/issues/33

I'd generally aim to get the desktop app and web app as close together as possible, so things won't have to be developed twice.

**Comment by roipoussiere** [comment]
> As of now, the welcome message will only appear once. As soon as you select another tab or close the bottom bar, it will stay that way. the same goes for the settings (including theme) and code in the editor. Not sure if that's really needed then.

I think there are some use cases where it's interesting to have some options directly set on the first run, for instance to have different ui setups depending on some context, but anyway.

> there is a prototype for vs code somewhere. but in many cases, it can be tricky to get the highlighting right.

Do you know where? I'm a VSCode user, I would like to give a try. :)

> I'd generally aim to get the desktop app and web app as close together as possible, so things won't have to be developed twice.

Sure!

**Comment by roipoussiere** [comment]
So I published [a VSCode extension](https://marketplace.visualstudio.com/items?itemName=roipoussiere.tidal-strudel) that meets the need of a desktop app! :)

So I'm not sure anymore it's necessary to distribute a desktop version of the strudel app, as it will add more complexity to the project compared to its utility (I will not work on this anyway).

**Comment by felixroos** [comment]
> So I'm not sure anymore it's necessary to distribute a desktop version of the strudel app, as it will add more complexity to the project compared to its utility (I will not work on this anyway).

Which features of the desktop app could the VSCode extension replace? Can we use it as a file / midi / osc / link server?
I still think a desktop app would be great to have someday, as not everybody uses VSCode and it is still a good thing to have editor / docs / custom UI in one package. But it is also not something I would focus on right now

**Comment by felixroos** [comment]
this is done with https://github.com/tidalcycles/strudel/pull/613 !
