### ISSUE TITLE
Adaptive Highlighting

### ISSUE THREAD

**Issue by mindofmatthew** [tidalcycles/strudel#632]
Picking up on #178, I think that storing code positions outside of the Codemirror state is a questionable idea. Within the world of codemirror extensions, everything that could potentially refer to a code location is set up to that it can automatically transform across document changes. Storing code locations in Strudel patterns breaks that and is related to the issue where editing code doesn't update highlight positions.

I think the better approach (which I'm going to try for Tidal highlights) is to generate ids for each mininotation symbol and then pass a mapping of ids to code positions into a codemirror extension at the point of evaluation. Then those ids would be saved in the pattern as event context, and the codemirror extension could keep track of moving annotations in sync with document edits.

I'd be happy to work on the codemirror extension side of things, but is this something that would be easy to do when Strudel code is evaluated?

This probably has a lot of overlap with #560.

**Comment by felixroos** [comment]
> Picking up on https://github.com/tidalcycles/strudel/issues/178, I think that storing code positions outside of the Codemirror state is a questionable idea.

It was a good starting point to get the highlighting working at least. But I agree that it would be amazing if the highlighting would dynamically adapt to changes in the code (and not stay where the code was at eval time).

> This probably has a lot of overlap with https://github.com/tidalcycles/strudel/issues/560.

This should already be fixed with https://github.com/tidalcycles/strudel/tree/main/packages/codemirror tho the REPL still uses the react hook, not sure if it needs to be refactored

> I think the better approach (which I'm going to try for Tidal highlights) is to generate ids for each mininotation symbol and then pass a mapping of ids to code positions into a codemirror extension at the point of evaluation.

sounds reasonable. this would need to happen in the [transpiler](https://github.com/tidalcycles/strudel/blob/f07859996eecec898f8fc3ec716b0e8a03f82b7b/packages/transpiler/transpiler.mjs#L6), meaning that the transpiler will not only return the transpiled code, but also an some form of id / location mapping.

Here is an example of what the transpiler does atm:

```js
"c3 [e3 g3]*2"
```

will be transpiled into

```js
mini("c3 [e3 g3]*2").withMiniLocation([1,0,0],[1,14,14])
```

Additionally, the `mini` function uses the `patternifyAST` function, which will set the location of each substring at eval time, creating the call structure of:

```js
seq(
  reify('c3').withLocation([1,1,1], [1,4,4]),
  seq(
    reify('e3').withLocation([1,5,5], [1,8,8]),
    reify('g3').withLocation([1,8,8], [1,10,10]),
  ).fast(2)
)
.withMiniLocation([1,0,0],[1,14,14]) // <-- added after mini("c3 [e3 g3]*2")
```

The absolute location of each substring is the sum of `withLocation` and `withMiniLocation`, translating the local position obtained from the mini parser (withLocation) into the global position obtained from the js parser (withMiniLocation).

And this is where it gets problematic: We cannot use ids with this approach, because we basically have 2 locations that are summed at eval time, so we only know the location of the whole mini string at transpile time..

But I wonder if we really need ids with an loc mapping..
Wouldn't codemirror only need the information *when* the evaluation happened, so that it could remap the summed locs accordingly? Codemirror would need to be able to translate a past loc at a known past state to the current loc in the current state (which sounds to me as if it would be enough information). I don't know enough about how codemirror does the change mapping, so I don't know if this is possible.

If it's not possible, the transpiler would need to work with the mini parser to construct the resulting call structure as an AST.. so basically do what `patternifyAST` does, but not calling functions directly but construct the syntax of the calls and generate source code from it. this is doable, but not really needed if the problem can be solved otherwise.. 

This is just me thinking out loud.. What do you think?

**Comment by felixroos** [comment]
btw the format of the locs is currently:

```
[
line,  // line starting from 1
column, // character inside line, starting from zero
offset // character inside whole document, starting from zero
]
```

this has historical reasons (cm5). it could be simplified to only use the offset. There is already a `simpleLocs` flag in the transpiler, which will turn

```js
stack(
  s("bd"),
  s("hh oh")
)
```

into

```js
stack(
  s(mini("bd").withMiniLocation(11, 15)),
  s(mini("hh oh").withMiniLocation(22, 29))
);
```

instead of 

```js
stack(
  s(mini("bd").withMiniLocation([2, 4, 11], [2, 8, 15])),
  s(mini("hh oh").withMiniLocation([3, 4, 22], [3, 11, 29]))
);
```

**Comment by felixroos** [comment]
maybe there is a way to at least get the locations at eval time:

instead of doing:

```js
stack(
  s(mini("bd").withMiniLocation(11, 15)),
  s(mini("hh oh").withMiniLocation(22, 29))
);
```

there could be a `miniWithLocation` function used like this:

```js
stack(
  s(withMiniLocation("bd", 11, 15)),
  s(withMiniLocation("hh oh", 22, 29)),
);
```

That function could then calculate the sum directly, resulting these calls:

```js
stack(
  s(reify('bd').withLocation(12, 14)),
  s(seq(reify('hh').withLocation(23,25), reify('oh').withLocation(26,28))),
);
```

not sure if this would be any useful in this issue, but generally it would be more efficient and simple

**Comment by mindofmatthew** [comment]
To be clear, I totally agree that getting a working version of the highlighting so early was awesome, and that prototyping and iterating is always better than trying to design a "perfect" implementation from scratch.

> But I wonder if we really need ids with an loc mapping..
Yeah, I mean "ID" loosely, and the ID can be "the code location when the code was originally transpiled". The point here is just to think of this data as, like, a fingerprint rather than as the source of truth for code position.

The one thing I'd add to `withMiniLocation` would be some sort of increasing index that indicates which update/evaluation triggered the transpile. This isn't useful for the current editor, but would probably be necessary with block-based evaluation, where you'd have blocks that were transpiled at different times moving around the document.

Thanks for the description, by the way—I understand the individual steps a lot better now. Rather than complicating the transpile side, it might be better to build some separate logic that hooks into the CodeMirror JS parser. That parser could be extended to parse the mininotation, which could lead to mininotation syntax highlighting (!). This probably means some duplicated parsing logic, which feels awkward, but we already have mininotation parsers in multiple languages, and developing a spec and test suite to ensure standardization would be very useful.

**Comment by mindofmatthew** [comment]
Also, I strongly support moving to the `simpleLocs` format for everything. [CodeMirror has good utility functions for converting offsets to lines and columns](https://codemirror.net/docs/ref/#state.Text), so storing that data explicitly isn't necessary.

**Comment by felixroos** [comment]
> Rather than complicating the transpile side, it might be better to build some separate logic that hooks into the CodeMirror JS parser

afaik codemirror only has a tokenizer for syntax highlighting, but maybe it's enough..

> That parser could be extended to parse the mininotation, which could lead to mininotation syntax highlighting (!)

cool idea

I couldn't help but try some things out and I might be on to something here: https://github.com/tidalcycles/strudel/blob/highlight-ids/packages/mini/test/mini.test.mjs#L208

This allows resolving the locations of all leaf nodes in the mini notation ast at transpile time. the absolute location of each leaf could then be calculated by summing the result of `getLeafLocations` with the location of the mini string [already known in the transpiler](https://github.com/tidalcycles/strudel/blob/main/packages/transpiler/transpiler.mjs#L71). so no need for weird ways of communication at eval time. the repl could just pass the leaf locations (or an index to location mapping) to codemirror. 

Instead of using indices, I also like the idea of using the location itself as id, as it is unique, e.g. "1:3" or "10:12". This would still allow using the locations in a static way without needing to use the emitted locations from the transpiler. not sure yet tho

> Also, I strongly support moving to the simpleLocs format for everything. [CodeMirror has good utility functions for converting offsets to lines and columns](https://codemirror.net/docs/ref/#state.Text), so storing that data explicitly isn't necessary.

yup, but using cols only only makes sense when the editor supports the dynamic remapping of locations. if it does not, using columns only worsens the offsets. currently (with [line offset col]) the highlighting only breaks after the cursor in the same line or after the cursor in all following lines if a line is inserted. when only columns are used, any character entered would break the highlights after the cursor (i think)

**Comment by felixroos** [comment]
it is now possible to get all absolute mini locations at transpile time: https://github.com/tidalcycles/strudel/blob/5f271ed12779abd92cfab0f7976750d7b7088e2d/packages/transpiler/test/transpiler.test.mjs#L39

to bubble those miniLocations up to codemirror the route would be:

- pass out miniLocations from [core/evaluate](https://github.com/tidalcycles/strudel/blob/f07859996eecec898f8fc3ec716b0e8a03f82b7b/packages/core/evaluate.mjs#L41)
- emit miniLocations from [repl.afterEval](https://github.com/tidalcycles/strudel/blob/f07859996eecec898f8fc3ec716b0e8a03f82b7b/packages/core/repl.mjs#L38)
- dispatch miniLocations to codemirror in Repl from [useStrudel.afterEval](https://github.com/tidalcycles/strudel/blob/f07859996eecec898f8fc3ec716b0e8a03f82b7b/website/src/repl/Repl.jsx#L131C7-L131C7)

still not sure how the codemirror part would work..

**Comment by felixroos** [comment]
> bubble those miniLocations up to codemirror

is now working! had to standardize the transpiler output to always be an object with .output and eventually .meta , where the miniLocations will be. that metadata is now emitted to [afterEval](https://github.com/tidalcycles/strudel/commit/8e717d2ea15398847b4b888d415f50722df42e79#diff-3e23fc49781b605934806fbca742fa80c7f9de9b4ba899b8dec61713bc0a78a5R132), so it could now be passed to codemirror from Repl.jsx .. only problem left is that afterEval is currently memoized, so it has no access to the codemirror view..

**Comment by felixroos** [comment]
I have tried to reimplement the highlighting to adapt to changes but I have trouble understanding how to do it with the codemirror API. It is certainly well thought out and everything, but having only very basic examples and a huge reference is not enough for me to understand how it is intended to be used... 

So far, I cannot find a way to update the existing DecorationSet... just pushed a [half working state](https://github.com/tidalcycles/strudel/commit/63c23736ade95bf7c1d2073afd87ba4ad04d2d8b) to the highlight-ids branch.. @mindofmatthew maybe you know how to do this? If not, I'll keep bashing my head against it when my frustration has decomposed

**Comment by felixroos** [comment]
found a [solution](https://github.com/tidalcycles/strudel/commit/0b5d905120e63cfee90c2e25c929a02b63d096b2#diff-fd688122a43fe602d5d0dbb4ff5ee5bf1fd7dd7875589a2d36e47820b207d85e)! there is probably / hopefully a more idiomatic way to solve this with codemirror, but for now, the highlighting will properly move when edits are made:

https://github.com/tidalcycles/strudel/assets/12023032/11c7592b-84ed-4bf4-845d-e4bcb6ed4e46

so the codemirror side should be fine with that, still the passing of the mini locations to codemirror is still hard coded..

**Comment by felixroos** [comment]
Here is the same example from above, showing what the transpiler does now:

```js
s("c3 [e3 g3]*2")
```

will be transpiled into

```js
s(m("c3 [e3 g3]*2", 2))
```

So each double quoted string will be wrapped in `m(string, offset)` where offset is the location of the string in the JS code (2 in this case). 

The `m` function then uses `patternifyAST` to turn the string into a pattern, where each leaf node will have the location attached via `withLoc` (replacement for withLocation + withMiniLocation):

```js
seq(
  reify('c3').withLoc(3, 5),
  seq(
    reify('e3').withLoc(7, 9),
    reify('g3').withLocation(10, 12),
  ).fast(2)
)
```

Note that the locations passed to `withLoc` are already relative to the whole document, so no extra `withMiniLocation` is needed anymore! also, offsets (prior called simpleLocs) are now used everywhere instead of [line,col,offset].

So this is now the implementation of [this idea](https://github.com/tidalcycles/strudel/issues/632#issuecomment-1615954741), which feels much simpler and easier to grasp. Also, the transpiler output is much shorter.

While the above part only tells each hap where it is in the document, codemirror also needs to know all positions of mini notation substrings at evaluation time. To solve this, the transpiler now uses the `emitMiniLocations` flag, which will return `miniLocations` to the transpiler output. In the above example the value would be `[[3, 5], [7, 9], [10, 12]]`.

This works by calling `getLeafLocations` for each mini notation string, which returns the positions of all substrings / leaf nodes. This works via the `onEnter` callback of `patternifyAST`, allowing to resolve all leaf nodes and running the same `getLeafLocation` on them. The actual pattern returned by `patternifyAST` is not used in this case, which feels a bit strange. 

Maybe that last part could be solved more efficiently with [lezer](https://lezer.codemirror.net/), which is the parser that codemirror uses (it actually *is* a parser and not just a tokenizer...). Alternatively this could also be solved with a simple regex. Taking a JS string, detecting all double quoted strings and then detecting all substrings / numbers in it sounds not too difficult. It is not important that this logic will run in the same order as the mini parser. As long as the locations match up, it will work..

**Comment by felixroos** [comment]
just tested your changes, looks amazing! the opacity adds another layer of usefulness. But it could potentially worsen the performance on lower end devices, as it's now doing a dom update for every location every frame instead of only updating starts and ends of highlights. Maybe this should be a setting?
