### ISSUE TITLE
event > hap

### ISSUE THREAD

**Issue by yaxu** [tidalcycles/strudel#94]
Events are called 'haps' in strudel, mainly because the word `event` is already taken.

However we still call them events in secondary notation (variable/function names and comments).

We should probably do a (careful) search and replace on everything. Or is it OK to use the terms interchangeably?

**Comment by felixroos** [comment]
I would say using them interchangeably is ok, because the term event is so universal. But we can also do a replacement, though I cannot promise that my fingers wont type the word event ever again.

I also had the more general idea that we could add some kind of explainer for the different words used and the concepts behind them

**Comment by yaxu** [comment]
Ok lets not worry for now
